- pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go
Many orgs have multiple repos that are forks and archived. adding `isArchived: false` and `isFork: false` to the `repositories` query reduces the overhead of getting metrics on non-maintained repositories and increases performance by reducing the amount of subsequent calls and iterations. This may be feature flagged via config in the future.
> fix: add ignore to archived and forked repositories on search

- catalog-info.yaml
❗ This is not ready to merge. Please review the changeset and update based on your repository. ❗
Please give the catalog-info.yaml a review. It could use tags, links, a description and the correct owner. Each section has links to the related documentation.
Review the [catalog-info.yaml docs](https://backstage.io/docs/features/software-catalog/descriptor-format/)
Check out an example of our implementation in [gratibot](https://github.com/liatrio/gratibot/blob/main/catalog-info.yaml)
After you've finished and merged, this repository will auto discover in the Liatrio Backstage instance.
For any questions, please reach out on our Slack channel: #project-backstage-foundations
> chore: create catalog-info.yaml for Backstage Auto Discovery

- catalog-info.yaml
I noticed the otel collector wasn't showing up in Backstage because of a minor issues with the tags:
```
iatrio-backstage-node-1  | [1] 2023-09-11T20:21:04.988Z catalog warn Policy check failed for component:default/liatrio-otel-collector; caused by Error: "tags.6" is not valid; expected a string that is sequences of [a-z0-9+#] separated by [-], at most 63 characters in total but found "open source"
```
With this change, the catalog info file validated successfully for me locally using the [entity-validator](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/utils/roadie-backstage-entity-validator)
> build: fix Backstage catalog info links

- pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/config.go
- pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/config_test.go
As the `config.go` file only exports/contains the Config struct, I added a test that'll create a config using the exported struct and one using the factory.CreateDefaultConfig() and compare them to ensure they match up, meaning the exported struct is "ok".
> test: added a test for `config.go`

- pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/factory_test.go
This commit, & subsequent PR, add tests for the `factory.go` file to cover the two functions it exports.
> test: added tests for `factory.go`

- .codecov.yml
- .github/codecov.yml
- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/generated.go
- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/genqlient.graphql
- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/gitlab_scraper.go
Was hardcoded as "main" and some repos don't use that as the default branch so it errors out
> fix: grabbing default branch from api to compare to

- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/config.go
- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/generated.go
- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/gitlab_scraper.go
This PR adds the ability to filter down the projects returned by the GitLab API for a group by providing a topic and/or search query to the request.
> feat: added support for filtering projects by topic & search query

- pkg/receiver/gitproviderreceiver/internal/scraper/gitlabscraper/gitlab_scraper_test.go
I could use some insight on practical test cases. I have hit all the lines of code but the tests are not very significant.
> test: add tests for gitMergeRequests

- pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go
Fix errors when using on-premise endpoints.
When GHE (GitHub on Premise) is addressed, scrape(...) method crashed because :
- getContributorCount is always called even when git.repository.contributor.count is disabled.
(#159)
- the restCURL was not computed correctly when the endpoint is defined with api path
(`endpoint: "https://ghetest.mycompany.grp:443/api"`)
Close #165, #156
> fix: Endpoint management for GitHub enterprise (ghe)

- pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go
Analysis:
The function processCommits() crashes in github_scraper.go#L252
- `oldest := e[len(e)-1].Node.GetCommittedDate()` crashes because of out of bound index (-1).
- the index is out of bound because `e := ct.History.GetEdges()` is empty.
- `ct.History.GetEdges()` is empty when `comCount` is equal to zero.
- `comCount` is equal to zero when the last page contains 100 commits.
close https://github.com/liatrio/liatrio-otel-collector/issues/177
> fix: Application crashes when adressing a specific organization

- config/config.yaml
The environment variable syntax in the `config.yaml` file was incorrect. It used a '.' instead of a ':'. This commit fixes that issue by changing `${env.GITHUB_ORG}` to `${env:GITHUB_ORG}`.
> fix(config): correct environment variable syntax in config.yaml

- renovate.json
May look to leveraging self hosted renovate in favor of hosted due to the un-availability for the `postUpgradeOptions` command.
> chore(deps): update renovate config to add gomodTidy post update

- receiver/gitproviderreceiver/internal/scraper/gitlabscraper/helpers.go
I don't think we want to include Archived projects in Gitlab. They are read-only and will skew metrics if there are stale branches or merge requests at the time of archival.
> fix: Ignore archived projects in Gitlab scraper

- .github/workflows/build.yml
- .github/workflows/go-semantic-release.yml
- .github/workflows/scorecard.yml
This PR refines the continuous integration setup by enhancing the semantic release process. 
The following changes have been made:
- Added a condition to prevent workflows triggered by pushes to the main branch from executing if the GitHub actor is not the release bot.
- Triggered the semantic release workflow to run only after the "Build and Test" workflow completes, ensuring proper sequencing of tasks.
These updates streamline the workflow and improve token handling for better security and automation control.
> ci: restructure semantic release workflow

- config/manifest.yaml
This PR will add two new processor plugins, focused on sampling, to the manifest. The goal being to reduce the volume of data being sent to the collector while still keeping important data. 
1. probabilisticsamplerprocessor: This plugin will allow users to sample traces based on a probability distribution. PSP uses a configured sampling percentage to determine which traces or logs to sample. [More info here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/probabilisticsamplerprocessor/README.md)
2. tailsamplingprocessor - The Tail Sampling Processor delays the sampling decision until all spans of a trace are available, enabling better sampling decisions based on the complete trace information. [More info …
> feat: add tail based and probabilistic sampling plugins 

- config/config.yaml
- extension/githubappauthextension/README.md
- receiver/githubreceiver/README.md
- receiver/githubreceiver/internal/scraper/githubscraper/factory.go
- receiver/githubreceiver/testdata/config.yaml
```yaml
github:
scrapers:
github: ...
```
has now been changed to:
```yaml
github:
scrapers:
scraper: ..
```
Resolves #570
> feat(refactor): update github receiver to use scraper as key

- receiver/gitlabreceiver/README.md
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/config.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/generated.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/genqlient.graphql
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/gitlab_scraper.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers_test.go
When dealing with repositories with a lot of history, there could be a significant number of merged merge requests. Some repositories could have thousands or tens of thousands of merged changes in their history. This can have a significant impact on the performance of the collector and will continue to grow over time. Also, knowing the metrics for merge requests from years in the past may not be relevant or helpful compared to the more recent past. 
To help with this problem, this pull request adds the `limit_merge_requests` configuration option. With it, you can filter merged merge requests to only those created within the last X number of days.
> feat: Add ability to limit query for merged merge requests in gitlab

- receiver/gitlabreceiver/go.mod
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/gitlab_scraper.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers_test.go
When configuring the gitlab receiver to scrape a group with either a large number of repositories or repositories with many branches, the performance can be pretty slow. This was due to the nature of the function used to loop over repositories in parallel. This parallel processing was somewhat limited by the use of the mutex lock/unlock at the beginning/end of the function. This effectively single-threaded the processing of each repository. 
By adding more precise lock/unlock calls it allows more parallel processing to occur and only lock execution when updating the metric builder. However, in allowing more parallel calls to be made for each repo, we quickly ran into rate limiting errors from the Gitlab API. I tried to mimic the rate limiting handling already implemented within the github …
> feat: Add rate limit retry to gitlab requests and better error messages when failures occur

- receiver/gitlabreceiver/internal/scraper/gitlabscraper/gitlab_scraper.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/gitlab_scraper_test.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers_test.go
I should have added the retry logic to the getProjects as well. I figured it was early enough in the process that it wouldn't be subjected to rate limiting. If you have multiple receivers configured to scrape multiple gitlab groups in parallel it's possible for one receiver to start making a large number of API calls. At that point, subsequent receivers could still fail on the initial API call to retrieve projects.
> fix: Add rate limit retry logic for gitlab getProjects function

- config/manifest.yaml
Updating manifest to use up-to-date component versions that are necessary for some upstream changes we are porting back
> chore: Update manifest

- receiver/gitlabreceiver/documentation.md
- receiver/gitlabreceiver/internal/metadata/generated_metrics.go
- receiver/gitlabreceiver/internal/metadata/generated_metrics_test.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/config.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/generated.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/genqlient.graphql
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/gitlab_scraper.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/gitlab_scraper_test.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/helpers.go
- receiver/gitlabreceiver/internal/scraper/gitlabscraper/testdata/scraper/expected_happy_path.yaml
- receiver/gitlabreceiver/metadata.yaml
Two main changes in this pull request:
1. The `vcs.repository.id` was added as an attribute to the relevant GitLab receiver metrics. This represents the unique, numerical ID for the repository. This is especially useful for any downstream processes that need to make GitLab API calls to enrich the data. Most API calls are based on the numerical ID as opposed to the string namespace. 
2. The limiter functionality from the github receiver was added to the gitlab receiver. This is useful in limiting the concurrent number of API calls being made to GitLab. By specifying the `concurrency_limit` option, you limit the number of GitLab projects that can be processed in parallel.
> feat: Add project ID to gitlab attributes and include concurrency limit
